[package]
name = "simplepush-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
rand = "0.8.3"
reqwest = { version = "0.12.4", features = ["blocking", "json"] }
rust-crypto = "0.2.36"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"